add configuration file
in0rdr/diary pull request #61
Opened 2021-01-03 22:35 UTC by in0rdr

This adds a basic config file, see https://github.com/in0rdr/diary/issues/35

Currently, it allows to configure:
- diary_dir
- year_range
- first_weekday
- date_fmt

2021-01-04 00:15 UTC, bovine3dom reviewed
Just some initial bike-shedding - I'll try to check the code for correctness another day.

(Please ping me if I leave it too long : ) !)

2021-01-04 00:15 UTC, bovine3dom commented on diary.cfg
> +diary_dir = /tmp/diary
```suggestion
diary_dir = ~/diary
```

I know this is just an example configuration but I think "lose all diary entries on PC restart" is guaranteed to surprise and upset someone.

2021-01-04 00:15 UTC, bovine3dom commented on diary.c
>              case 'g':
It's probably worth making these configurable - e.g. for people with exotic keyboard layouts.

That said, I've no idea how to correctly handle keypresses from keyboards that generate UTF-8 like Cyrillic ones.

2021-01-04 11:13 UTC, bovine3dom commented on README.md
> +## Configuration File
We should document this on the man page too.

2021-01-04 20:33 UTC, in0rdr commented on diary.h
> +#define CONFIG_FILE_PATH "~/.config/diary/diary.cfg"
of course, I suppose you meant the [`$XDG_CONFIG_HOME`](https://wiki.archlinux.org/index.php/XDG_Base_Directory) and amended the code

2021-01-04 20:51 UTC, in0rdr commented on README.md
> +## Configuration File
Definitively, I added the binary and the config file to the files section of the man page and checked with `nroff -man diary.1 | less`

2021-01-04 20:54 UTC, in0rdr commented on diary.c
>              case 'g':
Agree, but I don't know how to implement this straight off my head. For now, I added this as an issue: https://github.com/in0rdr/diary/issues/65

2021-01-04 21:46 UTC, in0rdr commented
> Just some initial bike-shedding - I'll try to check the code for correctness another day.
> 
> (Please ping me if I leave it too long : ) !)

Your review is much appreciated.

In addition to the existing changes, I've add the range (`-r`), weekday (`-w`) and fmt (`-f`) options to be consistent with the keys in the config file.

2021-01-04 23:07 UTC, bovine3dom commented on diary.1
> +An optional diary configuration file
I think we should really explain the options here. If anything I'd argue that the man page should be more detailed than readme.md since the readme is more for developers and to persuade people to download and install the package. The man page is used by people who want to work out how to use it : )

2021-01-07 10:05 UTC, bovine3dom requested changes
Just a couple of things I noticed while testing.

Aside from that and my other comments (I think that the man page could be more extensive) this looks good to me : )

2021-01-07 10:05 UTC, bovine3dom commented on diary.cfg
> +date_fmt = %d_%b_%y
Can I suggest having the default config just set all of these things to their defaults? This one in particular caught me out. Perhaps suggest different settings with a comment

2021-01-07 10:05 UTC, bovine3dom commented on diary.cfg
> +diary_dir = ~/diary
`~` doesn't work on my system (Arch Linux) - I get "Directory '~/diary' does not exist".

2021-01-07 22:47 UTC, in0rdr commented on README.md
> +## Configuration File
pushed a commit that holds a section for OPTIONS and more details on how to bootstrap a simple config file

2021-01-07 22:48 UTC, in0rdr commented on diary.cfg
> +date_fmt = %d_%b_%y
pushed a commit that sets the values to their defaults

2021-01-07 23:06 UTC, in0rdr commented on diary.cfg
> +diary_dir = ~/diary
yup, that's because the string from the file is not expanded, which is the case if you provide it via argument or option `-d`. I pushed a commit which expands the value from the config file as well.

2021-01-07 23:09 UTC, in0rdr commented
Thanks for the second round of review, I really appreciate it, because the documentation is only getting better, I think.

Also, I'd like to change the format of the options. I am not yet happy with the underscore style.

For instance, I want to change from `--year_range` to `--year-range` (same for the config file).

Therefore, I marked this as WIP again.

2021-01-08 08:39 UTC, bovine3dom commented on diary.c
> +  printf("  -r, --year_range    RANGE     : RANGE is the number of years to show before/after todays date\n");
```suggestion
  printf("  -r, --year_range    RANGE     : RANGE is the number of years to show before/after today's date\n");
```

2021-01-09 05:10 UTC, in0rdr commented
thanks! I'd like to add `EDITOR` as option and config parameter as well (note to self)

2021-01-17 15:17 UTC, in0rdr commented
Options simplified, documentation added. Todo, note to self, document `_NL_TIME_FIRST_WEEKDAY`:
```bash
export LANG=de_CH
# starts with weekday=1
./diary
unset LANG
printenv | grep -i lang
LANGUAGE=
# starts with weekday=0
./diary
```

2021-01-17 15:17 UTC, in0rdr commented
todo: order option arguments and config file keys in alphabetic order

2021-02-07 15:18 UTC, bovine3dom reviewed
I haven't looked at the code yet - just some suggestions for docs.

Otherwise this looks good : )

2021-02-07 15:18 UTC, bovine3dom commented on README.md
> +If glibc is installed, the first weekday defaults to the locale defined in the current shell environment (`$LANG`, see `man locale`), unless specified otherwise via the `--wekday` / `-w` command line
```suggestion
If glibc is installed, the first weekday defaults to the locale defined in the current shell environment (`$LANG`, see `man locale`), unless specified otherwise via the `--weekday` / `-w` command line options. For example:
```

2021-02-07 15:18 UTC, bovine3dom commented on diary.1
> +First day of the week. DAY is an integer in range (0..6), interpreted as 0 = Sun,
```suggestion
First day of the week. DAY is an integer in range (0..6), interpreted as 0 or 7 = Sun,
```

The idea of a `0`th day of the week is surprising to me. Could we make it support`7`, too? I think that would make it more intuitive without offending people who think you should count from zero : )

2021-02-07 15:18 UTC, bovine3dom commented on diary.1
> +environment ($LANG, see man locale), unless specified otherwise via the '--wekday'/'-w'.
```suggestion
environment ($LANG, see man locale), unless specified otherwise via the '--weekday'/'-w'.
```

2021-02-07 15:18 UTC, bovine3dom commented on diary.c
> +    if (cal_start.tm_wday != CONFIG.weekday) {
This sounds like Sunday = 7 is already supported?

2021-02-07 15:18 UTC, bovine3dom commented on diary.c
>    printf("Full docs and keyboard shortcuts: DIARY(1)\n");
```suggestion
  printf("Full docs and keyboard shortcuts: man \'DIARY(1)\'\n");
```

I think this is friendlier to people new to Linux

2021-02-07 15:18 UTC, bovine3dom commented on diary.cfg
> +editor = ""
```suggestion
editor = "nano"
```

May as well make it useful and friendly to beginners

2021-02-07 15:18 UTC, bovine3dom commented on README.md
> +The default variables, for instance, for the configuration variables `editor`, `dir` and `weekday`, are populated with values in the following order:
```suggestion
The default variables, for instance, for the configuration variables `editor`, `dir` and `weekday`, are populated with values in the following order, where earlier entries are overwritten by subsequent ones if they exist:
```

2021-02-08 21:10 UTC, in0rdr commented on diary.cfg
> +editor = ""
That's a good idea. But unfortunately it would destroy the nice read-only side-effect of not setting any editor (the pristine default behavior, so to say). Let's leave this as is for now.

2021-02-08 21:12 UTC, in0rdr commented on diary.c
>    printf("Full docs and keyboard shortcuts: DIARY(1)\n");
You are right, thanks. I just pushed a similar commit.

2021-02-08 21:22 UTC, in0rdr commented on diary.c
> +    if (cal_start.tm_wday != CONFIG.weekday) {
mh, yes, seems like it's somehow supported :) I am slowly at the point, were I now longer grok all the ins and outs of this codebase, especially the older parts. That was never my intention, but, what can you do? Maybe I'll have to organize it in several files for better coherence..

I tested with `diary -w0` and `diary -w7`, this is the same (Sun) start of the week. Then, with `diary -w1` and ``diary -w8` (and so on) it is the same behavior as well.

2021-02-08 21:22 UTC, in0rdr commented on diary.1
> +environment ($LANG, see man locale), unless specified otherwise via the '--wekday'/'-w'.
Thank you!

2021-02-08 21:28 UTC, in0rdr commented on diary.1
> +First day of the week. DAY is an integer in range (0..6), interpreted as 0 = Sun,
Perfect, I believe that already works with the current implementation. I'll update the docs in the other places as well. Makes more sense indeed, now, that I think about it :) Thanks

2021-02-21 06:44 UTC, bovine3dom approved these changes
Looks good to me : )

2021-02-24 06:38 UTC, merged